apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "bind-dns.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bind-dns.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      roll: {{ randAlphaNum 5 | quote }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bind-dns.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      initContainers:    # introducing init container to copy zone into /etc/bind/zones as an empty directory editable
      - name: init-config
        image: busybox
        command: ['sh', '-c', 'cp /config-source/* /etc/bind/zones/']
        volumeMounts:
        - name: bind-zone-config
          mountPath: /config-source
        - name: bind-zones
          mountPath: /etc/bind/zones       
      containers:
        - name: {{ .Values.name }}-bind
          image: {{ .Values.image.image }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              chown -R bind:bind /etc/bind/zones
              /usr/sbin/named -g -u bind
          securityContext: # security context introduced to run as root temporarily to fix permissions
            runAsUser: 0
          ports:
            - name: dns-tcp
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
            - name: dns-udp
              containerPort: {{ .Values.service.targetPort }}
              protocol: UDP
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            tcpSocket:
              port: dns-tcp
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          livenessProbe:
            tcpSocket:
              port: dns-udp
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: bind-config
            mountPath: /etc/bind
          - name: bind-zones
            mountPath: /etc/bind/zones
         #- name: bind-zone-config
         #   mountPath: /var/lib/bind
      volumes:
        - name: bind-config
          configMap:
            name: bind-config
            items:
              - key: named.conf
                path: named.conf
        - name: bind-zone-config
          configMap:
            name: bind-zone-config
                  {{- toYaml .Values.zoneconfigs | nindent 12 }}
        - name: bind-zones
          emptyDir: {}
