---
# Source: bind-dns/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: bind-config
data:
  named.conf: "options {\n        directory \"/var/cache/bind\";\n        listen-on
    port 53 { any; };\n        auth-nxdomain yes;\n        forwarders { \n                1.1.1.1;
    \n                1.0.0.1; \n        };\n        listen-on-v6 { any; };\n        allow-query
    { any; };\n        allow-recursion {\n                any;\n        };\n        allow-transfer
    {\n                none;\n        };\n        allow-update {\n                any;\n
    \       };\n};\n\nzone \"ML1.internal\" {\n  type master;\n  file \"/var/lib/bind/ML1.internal\";\n};\n"
---
# Source: bind-dns/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: bind-zone-config
data:
  ML1.internal: |
    $TTL    604800
    @       IN      SOA     ns1.ML1.internal. admin.ML1.internal. (
                                  5         ; Serial
                             604800         ; Refresh
                              86400         ; Retry
                            2419200         ; Expire
                             604800 )       ; Negative Cache TTL
  
    @                        IN      NS      ns.ML1.internal.
    ns                       IN      CNAME   bind-dns-udp.default.svc.cluster1.local
    rke00.mgr                IN      A       10.24.0.99
    rke01.mgr                IN      A       10.24.0.100
    rke-lb.mgr               IN      A       100.69.29.9
---
# Source: bind-dns/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: bind-dns-tcp
  labels:
    helm.sh/chart: bind-dns-0.1.0
    app.kubernetes.io/name: bind-dns
    app.kubernetes.io/instance: bind-dns
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
  selector:
    app.kubernetes.io/name: bind-dns
    app.kubernetes.io/instance: bind-dns
---
# Source: bind-dns/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: bind-dns-udp
  labels:
    helm.sh/chart: bind-dns-0.1.0
    app.kubernetes.io/name: bind-dns
    app.kubernetes.io/instance: bind-dns
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
  selector:
    app.kubernetes.io/name: bind-dns
    app.kubernetes.io/instance: bind-dns
---
# Source: bind-dns/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind-dns
  labels:
    app.kubernetes.io/name: bind-dns
    app.kubernetes.io/instance: bind-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bind-dns
      app.kubernetes.io/instance: bind-dns
  template:
    metadata:
      roll: "606DG"
      labels:
        app.kubernetes.io/name: bind-dns
        app.kubernetes.io/instance: bind-dns
    spec:
      affinity:
        null
      containers:
        - name: bind-dns-bind
          image: internetsystemsconsortium/bind9:9.21
          imagePullPolicy: IfNotPresent
          ports:
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
          resources:
            null
          volumeMounts:
          - name: bind-config
            mountPath: /etc/bind
          - name: bind-zone-config
            mountPath: /var/lib/bind
      volumes:
        - name: bind-config
          configMap:
            name: bind-config
            items:
              - key: named.conf
                path: named.conf
        - name: bind-zone-config
          configMap:
            name: bind-zone-config
            items:
            - key: ML1.internal
              path: ML1.internal
---
# Source: bind-dns/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "bind-dns-test-connection"
  labels:
    helm.sh/chart: bind-dns-0.1.0
    app.kubernetes.io/name: bind-dns
    app.kubernetes.io/instance: bind-dns
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['bind-dns:53']
  restartPolicy: Never
