---
# Source: bind-dns/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: externaldns-tsig-secret
type: Opaque
data:
  tsig-secret: N2R2c2NEUTBlNnB3dFFLY2xwNEZVQ0RYY1hVWE1KQlphRWQ1cUNDWWxxTT0=
---
# Source: bind-dns/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: bind-config
data:
  named.conf: "options {\n        directory \"/var/cache/bind\";\n        listen-on
    port 53 { any; };\n        auth-nxdomain yes;\n        forwarders { \n                1.1.1.1;
    \n                1.0.0.1; \n        };\n        listen-on-v6 { any; };\n        allow-query
    { any; };\n        allow-recursion {\n                any;\n        };\n        allow-transfer
    {\n                any;\n        };\n        allow-update {\n                any;\n
    \       };\n};\nkey \"externaldns-key\" {\n    algorithm hmac-sha256;\n    secret
    \"NI5Pc2N0JM+lWiWsCBU38SJysdmkrvGn0VfifD6uup0=\";\n};\n\n#    key \"externaldns-key\"
    {\n#    algorithm hmac-sha256;\n#    secret \"7dvscDQ0e6pwtQKclp4FUCDXcXUXMJBZaEd5qCCYlqM=\";\n#
    };\nzone \"ML1.internal\" {\n  type master;\n  file \"/etc/bind/zones/ML1.internal\";\n
    \ allow-update { key \"externaldns-key\";};\n};\n"
---
# Source: bind-dns/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: bind-zone-config
data:
  ML1.internal: |
    $TTL    604800
    @       IN      SOA     ns1.ML1.internal. admin.ML1.internal. (
                                  5         ; Serial
                             604800         ; Refresh
                              86400         ; Retry
                            2419200         ; Expire
                             604800 )       ; Negative Cache TTL
  
    @                        IN      NS      ns.ML1.internal.
    rke00.mgr                IN      A       10.24.0.99
    rke01.mgr                IN      A       10.24.0.100
    rke-lb.mgr               IN      A       100.69.29.9
---
# Source: bind-dns/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: bind-dns-tcpudp
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ns.ML1.internal.
    external-dns.alpha.kubernetes.io/ttl: "300"
  labels:
    helm.sh/chart: bind-dns-0.1.0
    app.kubernetes.io/name: bind-dns
    app.kubernetes.io/instance: bind-dns
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
  selector:
    app.kubernetes.io/name: bind-dns
    app.kubernetes.io/instance: bind-dns
---
# Source: bind-dns/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind-dns
  labels:
    app.kubernetes.io/name: bind-dns
    app.kubernetes.io/instance: bind-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bind-dns
      app.kubernetes.io/instance: bind-dns
  template:
    metadata:
      roll: "iICWy"
      labels:
        app.kubernetes.io/name: bind-dns
        app.kubernetes.io/instance: bind-dns
    spec:
      affinity:
        null
      initContainers:    # introducing init container to copy zone into /etc/bind/zones as an empty directory editable
      - name: init-config
        image: busybox
        command: ['sh', '-c', 'cp /config-source/* /etc/bind/zones/']
        volumeMounts:
        - name: bind-zone-config
          mountPath: /config-source
        - name: bind-zones
          mountPath: /etc/bind/zones       
      containers:
        - name: bind-dns-bind
          image: internetsystemsconsortium/bind9:9.21
          imagePullPolicy: IfNotPresent
          securityContext: # security context introduced to run as root temporarily to fix permissions
            runAsUser: 0
    #     command:
    #        - /bin/sh
    #        - -c
    #        - |
    #          chown -R bind:bind /etc/bind/zones
          ports:
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
          resources:
            null
          volumeMounts:
          - name: bind-config
            mountPath: /etc/bind
          - name: bind-zones
            mountPath: /etc/bind/zones
         #- name: bind-zone-config
         #   mountPath: /var/lib/bind
      volumes:
        - name: bind-config
          configMap:
            name: bind-config
            items:
              - key: named.conf
                path: named.conf
        - name: bind-zone-config
          configMap:
            name: bind-zone-config
            items:
            - key: ML1.internal
              path: ML1.internal
        - name: bind-zones
          emptyDir: {}
---
# Source: bind-dns/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "bind-dns-test-connection"
  labels:
    helm.sh/chart: bind-dns-0.1.0
    app.kubernetes.io/name: bind-dns
    app.kubernetes.io/instance: bind-dns
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['bind-dns:53']
  restartPolicy: Never
